AllCops:
  TargetRubyVersion: 2.5.3

require:
  - rubocop-rspec
  - rubocop-performance

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Metrics/AbcSize:
  Max: 27

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 11

Metrics/ClassLength:
  Exclude:
    - 'lib/sauce_bindings/options.rb'

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 17

Metrics/ModuleLength:
  CountComments: false
  Exclude:
    - 'spec/**/*'

Style/Documentation:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/FilePath:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/DescribedClass:
  EnforcedStyle: explicit